package org.example.repository

// Aurora DSQL favours UUID primary keys over auto-increment, so the id is a
// String holding the UUID generated by `gen_random_uuid()`.
data class UserModel(val id: String, val name: String, val email: String)
